image: maven:3-jdk-8

stages:
  - init
  - test
  - build
  - deploy

init:
  stage: init
  script: "mvn clean"
test:
  stage: test
  script: "mvn test"
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

build:
  script: "mvn clean install -B"
  
deploy:
  type: deploy
  script:
  - cd src/Server/TestServer
  - mvn package -DskipTests
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=area22gogreen --api-key=$HEROKU_API_KEY